# 1. Fetch list of users

GET /api/users/host/{{<host}}
> Accept: application/json
> User-Agent: katt
> Host: {{<hostname}}:{{<port}}
< 200
< Content-Type: application/json
{
    "count": "{{>user_count_1}}",
    "users": "{{_}}",
    "{{_}}": "{{unexpected}}"
}

# 2. Add new user

PUT /api/users/host/{{<host}}/username/{{<username}}
> User-Agent: katt
> Host: {{<hostname}}:{{<port}}
> Content-Type: application/json
{
    "user": {
        "password": "my_http_password"
    }
}
< 204

# 3. Fetch list of users again

GET /api/users/host/{{<host}}
> Accept: application/json
> User-Agent: katt
> Host: {{<hostname}}:{{<port}}
< 200
< Content-Type: application/json
{
    "count": "{{>user_count_2}}",
    "users": "{{_}}",
    "{{_}}": "{{unexpected}}"
}

# 4. Add him again (thus change his password) - check idempotency

PUT /api/users/host/{{<host}}/username/{{<username}}
> User-Agent: katt
> Host: {{<hostname}}:{{<port}}
> Content-Type: application/json
{
    "user": {
        "password": "some_other_password"
    }
}
< 204

# 5. Fetch list again

GET /api/users/host/{{<host}}
> Accept: application/json
> User-Agent: katt
> Host: {{<hostname}}:{{<port}}
< 200
< Content-Type: application/json
{
    "count": "{{<user_count_2}}",
    "users": "{{_}}",
    "{{_}}": "{{unexpected}}"
}

# 6. Add another user

PUT /api/users/host/{{<host}}/username/http_guy2
> User-Agent: katt
> Host: {{<hostname}}:{{<port}}
> Content-Type: application/json
{
    "user": {
        "password": "my_http_password"
    }
}
< 204

# 7. Fetch list again (expect 2 users now)

GET /api/users/host/{{<host}}
> Accept: application/json
> User-Agent: katt
> Host: {{<hostname}}:{{<port}}
< 200
< Content-Type: application/json
{
    "count": "{{>user_count_3}}",
    "users": "{{_}}",
    "{{_}}": "{{unexpected}}"
}


# 8. Delete him

DELETE /api/users/host/{{<host}}/username/{{<username}}
> User-Agent: katt
> Host: {{<hostname}}:{{<port}}
< 204

# 9. Delete the other too

DELETE /api/users/host/{{<host}}/username/http_guy2
> User-Agent: katt
> Host: {{<hostname}}:{{<port}}
< 204

# 10. Fetch list one more time

GET /api/users/host/{{<host}}
> Accept: application/json
> User-Agent: katt
> Host: {{<hostname}}:{{<port}}
< 200
< Content-Type: application/json
{
    "count": "{{<user_count_1}}",
    "users": "{{_}}",
    "{{_}}": "{{unexpected}}"
}
