type Query {
  "Contains all admin available queries"
  admin: AdminQuery
  "Contains all user available queries"
  user: UserQuery
}

type Mutation {
  "Contains all user available mutations"
  admin: AdminMutation
  "Contains all user available mutations"
  user: UserMutation
}


"""
Contains all admin available queries.
Only authenticated admin can execute this queries.
"""
type AdminQuery{
  "Get all enabled domains by hostType"
  domainsByHostType(hostType: String!): [String!]
  "Get information about the domain"
  domainDetails(domain: String!): Domain
}

"""
Contains all admin available mutations
Only authenticated admin can execute this mutations.
"""
type AdminMutation{
  "Add new domain"
  addDomain(domain: String!, hostType: String!): Domain
  "Remove domain"
  removeDomain(domain: String!, hostType: String!): RemoveDomainPayload
  "Enable domain"
  enableDomain(domain: String!): Domain
  "Disable domain"
  disableDomain(domain: String!): Domain
}


"""
Contains all user available queries.
Only authenticated user can execute this queries.
"""
type UserQuery{
}

"""
Contains all user available mutations.
Only authenticated user can execute this mutations.
"""
type UserMutation{
}

"""
A dynamic domain representation.
Some operation could return not complete object i.e. some fields can be null.
"""
type Domain{
  "Domain name"
  domain: String
  "Domain hostType"
  hostType: String
  "Is domain enabled?"
  enabled: Bool
}

"A result of domain removal"
type RemoveDomainPayload{
  "Success message"
  msg: String
  "Removed domain data"
  domain: Domain
}
