#!/bin/bash

VERSION=`../tools/generate_vsn.sh`

docker build -t $IMAGE_NAME \
             --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
	     --build-arg VCS_REF=${SOURCE_COMMIT} \
	     --build-arg VERSION=${VERSION} \
	     .
