#!/bin/bash

REPO_FETCH_URL=`git remote -v | grep origin | grep fetch | awk '{print $2}'`
if [[ ! "${REPO_FETCH_URL}" =~ ^http.* ]]; then
       #REPO URL doesn't start with http, try to rewrite it
       REPO_FETCH_URL=https://`echo ${REPO_FETCH_URL} | awk '{split($0,a,":"); split(a[1],b,"@"); print b[2]"/"a[2]}'`
fi
REPO_GIT_COMMIT=`git rev-parse --short HEAD`
GIT_COMMIT=${SOURCE_COMMIT:-$REPO_GIT_COMMIT}
BUILDER=mongooseim-builder
VOLUMES=`pwd`
mkdir builds

docker run -d --name ${BUILDER} -v ${VOLUMES}/builds:/builds mongooseim/mongooseim-builder:latest
docker exec -i ${BUILDER} /build.sh MongooseIM ${REPO_FETCH_URL} ${GIT_COMMIT}

cp builds/mongooseim*.tar.gz member/mongooseim.tar.gz

