"""
A dynamic domain representation.
Some operation could return incomplete object i.e. some fields can be null.
"""
type Domain{
  "Domain name"
  domain: DomainName
  "Domain hostType"
  hostType: String
  "Is domain enabled?"
  status: DomainStatus
}

"""
A domain representation with type.
Some operation could return incomplete object i.e. some fields can be null.
"""
type DomainWithType{
  "Domain name"
  domain: DomainName
  "Domain hostType"
  hostType: String
  "Is domain enabled?"
  status: DomainStatus
  "Domain source type"
  type: DomainType
}

enum DomainStatus {
  "Domain is enabled and ready to route traffic"
  ENABLED
  "Domain is disabled and won't be loaded into MongooseIM"
  DISABLED
  "Domain has been marked for deletion and is disabled until all data is removed"
  DELETING
  "Domain is deleted and does not exist anymore"
  DELETED
}

enum DomainType {
  "Domain is defined in the configuration file"
  STATIC
  "Domain is stored in the database"
  DYNAMIC
}
