enum MUCAffiliation{
  OWNER
  ADMIN
  MEMBER
  OUTCAST
  NONE
}

enum MUCRole{
  VISITOR
  PARTICIPANT
  MODERATOR
}

type MUCRoomUser{
  jid: JID
  nick: String!
  role: MUCRole!
}

type MUCRoomAffiliation{
  jid: JID!
  affiliation: MUCAffiliation!
}

type MUCRoomDesc{
  jid: JID!
  title: String!
  private: Boolean
  usersNumber: Int
}

type MUCRoomConfig{
  title: String!,
  description: String!,
  allowChangeSubject: Boolean!,
  allowQueryUsers: Boolean!,
  allowPrivateMessages: Boolean!,
  allowVisitorStatus: Boolean!,
  allowVisitorNickchange: Boolean!,
  public: Boolean!,
  publicList: Boolean!,
  persistent: Boolean!,
  moderated: Boolean!,
  membersByDefault: Boolean!,
  membersOnly: Boolean!,
  allowUserInvites: Boolean!,
  allowMultipleSession: Boolean!,
  passwordProtected: Boolean!,
  password: String!,
  anonymous: Boolean!,
  mayGetMemberList: [String!]!
  maxUsers: Int,
  logging: Boolean!,
}

input MUCRoomConfigInput{
  title: String,
  description: String,
  allowChangeSubject: Boolean,
  allowQueryUsers: Boolean,
  allowPrivateMessages: Boolean,
  allowVisitorStatus: Boolean,
  allowVisitorNickchange: Boolean,
  public: Boolean,
  publicList: Boolean,
  persistent: Boolean,
  moderated: Boolean,
  membersByDefault: Boolean,
  membersOnly: Boolean,
  allowUserInvites: Boolean,
  allowMultipleSession: Boolean,
  passwordProtected: Boolean,
  password: String,
  anonymous: Boolean,
  mayGetMemberList: [String!],
  maxUsers: Int
  logging: Boolean,
}

type MUCRoomsPayload{
  rooms: [MUCRoomDesc!]
  count: Int
  index: Int
  first: String
  last: String
}
