enum Affiliation{
  OWNER
  MEMBER
  NONE
}

input BlockingInput{
  entityType: BlockedEntityType!
  action: BlockingAction!
  entity: JID!
}

type BlockingItem{
  entityType: BlockedEntityType!
  action: BlockingAction!
  entity: JID!
}

enum BlockingAction{
  ALLOW,
  DENY
}

enum BlockedEntityType{
  USER,
  ROOM
}

input RoomConfigDictEntryInput{
  "The name of the config option"
  key: String!
  "Config option value"
  value: String!
}

type RoomConfigDictEntry{
  "The name of the config option"
  key: String!
  "Config option value"
  value: String!
}

type Room{
  jid: JID!
  name: String!
  subject: String!
  participants: [RoomUser!]!
  options: [RoomConfigDictEntry]
}

type RoomUser{
  jid: JID!
  affiliation: Affiliation!
}
