"Marks the resource to be accessed only by authorized requests"
directive @protected (type: String = ALL, args: [String!] = []) on FIELD_DEFINITION | OBJECT | INTERFACE

enum ProtectedType{
  DOMAIN
  ALL
}
