"""
Contains the modules and services used by the category or command.
"""
directive @use(
  "The list of modules used by the category or command"
  modules: [String!] = [],
  "The list of services used by the category or command"
  services: [String!] = [],
  "The list of internal databases used by the category or command"
  internal_databases: [String!] = [],
  "The argument names that contains domains or host types"
  args: [String!] = []
) on FIELD_DEFINITION | OBJECT
