"""
Allow user to generate upload/download URL for a file".
"""
type HttpUploadUserMutation @use(modules: ["mod_http_upload"]) @protected{
    "Allow user to generate upload/download URLs for a file"
    getUrl(filename: NonEmptyString!, size: PosInt!, contentType: String, timeout: PosInt!): FileUrls @use
}
