"""
Allow user to generate upload/download URL for the file".
"""
type HttpUploadUserMutation @protected{
    "Allow user to generate upload/download URLs for the file"
    getUrl(filename: String!, size: Int!, contentType: String!, timeout: Int!): FileUrls
}
