"""
Allow user to manage Multi-User Chat Light rooms.
"""
type MUCLightUserMutation @protected @use(modules: ["mod_muc_light"]){
  "Create a MUC light room under the given XMPP hostname"
  createRoom(mucDomain: DomainName!, name: String, subject: String, id: RoomName, options: [RoomConfigDictEntryInput!]): Room
    @use(arg: "mucDomain")
  "Change configuration of a MUC Light room"
  changeRoomConfiguration(room: BareJID!, name: String, subject: String, options: [RoomConfigDictEntryInput!]): Room @use(arg: "room")
  "Invite a user to a MUC Light room"
  inviteUser(room: BareJID!, recipient: JID!): String
    @use(arg: "room")
  "Remove a MUC Light room"
  deleteRoom(room: BareJID!): String
    @use(arg: "room")
  "Kick a user from a MUC Light room"
  kickUser(room: BareJID!, user: JID): String
    @use(arg: "room")
  "Send a message to a MUC Light room"
  sendMessageToRoom(room: BareJID!, body: String!): String
    @use(arg: "room")
  "Set the user blocking list"
  setBlockingList(items: [BlockingInput!]!): String
    @use
}

"""
Allow user to get information about Multi-User Chat Light rooms.
"""
type MUCLightUserQuery @protected @use(modules: ["mod_muc_light"]){
  "Get the MUC Light room archived messages"
  getRoomMessages(room: BareJID!, pageSize: PosInt, before: DateTime): StanzasPayload
    @use(arg: "room", modules: ["mod_mam_muc"])
  "Get configuration of the MUC Light room"
  getRoomConfig(room: BareJID!): Room
    @use(arg: "room")
  "Get users list of given MUC Light room"
  listRoomUsers(room: BareJID!): [RoomUser!]
    @use(arg: "room")
  "Get the list of MUC Light rooms that the user participates in"
  listRooms: [JID!]
    @use
  "Get the user blocking list"
  getBlockingList: [BlockingItem!]
    @use
}
