"""
Allow user to manage Multi-User Chat Light rooms.
"""
type MUCLightUserMutation @protected{
  "Create a MUC light room under the given XMPP hostname"
  createRoom(mucDomain: String!, name: String!, subject: String!, id: NonEmptyString): Room
  "Change configuration of a MUC Light room"
  changeRoomConfiguration(room: JID!, name: String!, subject: String!): Room
  "Invite a user to a MUC Light room"
  inviteUser(room: JID!, recipient: JID!): String
  "Remove a MUC Light room"
  deleteRoom(room: JID!): String
  "Kick a user from a MUC Light room"
  kickUser(room: JID!, user: JID): String
  "Send a message to a MUC Light room"
  sendMessageToRoom(room: JID!, body: String!): String
  "Set the user blocking list"
  setBlockingList(items: [BlockingInput!]!): String
}

"""
Allow user to get information about Multi-User Chat Light rooms.
"""
type MUCLightUserQuery @protected{
  "Get the MUC Light room archived messages"
  getRoomMessages(room: JID!, pageSize: Int, before: DateTime): StanzasPayload
  "Get configuration of the MUC Light room"
  getRoomConfig(room: JID!): Room
  "Get users list of given MUC Light room"
  listRoomUsers(room: JID!): [RoomUser!]
  "Get the list of MUC Light rooms that the user participates in"
  listRooms: [JID!]
  "Get the user blocking list"
  getBlockingList: [BlockingItem!]
}
