"""
Allow user to set own private
"""
type PrivateUserMutation @protected {
    setPrivate(elementString: String!): String
}

"""
Allow user to get own private
"""
type PrivateUserQuery @protected {
    getPrivate(element: String!, nameSpace: String!): String
}
