"""
Allow user to get information about sessions.
"""
type SessionUserQuery @protected{
  "List connected resources"
  listResources: [ResourceName!]
  "Count connected resources"
  countResources: Int
  "Get information about all sessions"
  listSessions: [Session!]
}
