"""
Allow user to query MAM archive.
"""
type StanzaUserQuery @protected{
  "Get n last messages to/from a given contact (optional) with limit and optional date"
  getLastMessages(with: JID, limit: PosInt = 50, before: DateTime): StanzasPayload
    @use(modules: ["mod_mam_pm"])
}

"""
Allow user to send messages.
"""
type StanzaUserMutation @protected{
  "Send a chat message to a local or remote bare or full JID"
  sendMessage(from: JID, to: JID!, body: String!): SendStanzaPayload
  "Send a headline message to a local or remote bare or full JID"
  sendMessageHeadLine(from: JID, to: JID!, subject: String, body: String): SendStanzaPayload
  "Send an arbitrary stanza"
  sendStanza(stanza: XmlElement): SendStanzaPayload
}

type StanzaUserSubscription @protected{
  "Subscribe to incoming messages"
  subscribeForMessages: StanzaMap
}
