"""
Allow user to get and revoke tokens.
"""
type Token {
  access: String
  revoke: String
}

type TokenUserMutation @protected{
  "Get a new token"
  requestToken: Token
  "Revoke any tokens"
  revokeToken: String
}
