schema{
  query: UserQuery,
  mutation: UserMutation
}

"""
Contains all user available queries.
Only an authenticated user can execute these queries.
"""
type UserQuery{
  "Check authorization status"
  checkAuth: UserAuthInfo
  "Account management"
  account: AccountUserQuery
  "MUC room management"
  muc: MUCUserQuery
  "MUC Light room management"
  muc_light: MUCLightUserQuery
  "Session management"
  session: SessionUserQuery
  "Stanza management"
  stanza: StanzaUserQuery
  "Roster/Contacts management"
  roster: RosterUserQuery
}

"""
Contains all user available mutations.
Only an authenticated user can execute these mutations.
"""
type UserMutation @protected{
  "Account management"
  account: AccountUserMutation
  "MUC room management"
  muc: MUCUserMutation
  "MUC Light room management"
  muc_light: MUCLightUserMutation
  "Stanza management"
  stanza: StanzaUserMutation
  "Roster/Contacts management"
  roster: RosterUserMutation
}
