schema{
  query: UserQuery,
  mutation: UserMutation
}

"""
Contains all user available queries.
Only an authenticated user can execute these queries.
"""
type UserQuery{
  "Check authorization status"
  checkAuth: UserAuthInfo
  "Account management"
  account: AccountUserQuery
  "Session management"
  session: SessionUserQuery
}

"""
Contains all user available mutations.
Only an authenticated user can execute these mutations.
"""
type UserMutation @protected{
  "Account management"
  account: AccountUserMutation
}
