"""
Allow user to set own vcard
"""
type VcardUserMutation @protected{
    "Set user's own vcard"
    setVcard(vcard: VcardInput!): Vcard
}

"""
Allow user to get user's vcard
"""
type VcardUserQuery @protected{
    "Get user's vcard"
    getVcard(user: JID): Vcard
}
