-define(GLOBAL_DISTRIB_MESSAGES_SENT, mod_global_distrib_outgoing_messages).
-define(GLOBAL_DISTRIB_MESSAGES_RECEIVED(Server), [mod_global_distrib, incoming, messages, Server]).
-define(GLOBAL_DISTRIB_TRANSFER_TIME(Server), [mod_global_distrib, incoming, transfer_time, Server]).
-define(GLOBAL_DISTRIB_SEND_QUEUE, mod_global_distrib_outgoing_queue).
-define(GLOBAL_DISTRIB_RECV_QUEUE_TIME, [mod_global_distrib, incoming, queue_time]).
-define(GLOBAL_DISTRIB_MAPPING_FETCHES, mod_global_distrib_mapping_fetches).
-define(GLOBAL_DISTRIB_MAPPING_CACHE_MISSES, mod_global_distrib_mapping_cache_misses).
-define(GLOBAL_DISTRIB_DELIVERED_WITH_TTL, mod_global_distrib_delivered_with_ttl).
-define(GLOBAL_DISTRIB_STOP_TTL_ZERO, mod_global_distrib_stop_ttl_zero).
-define(GLOBAL_DISTRIB_INCOMING_ESTABLISHED, [mod_global_distrib, incoming, established]).
-define(GLOBAL_DISTRIB_INCOMING_FIRST_PACKET(Server), [mod_global_distrib, incoming, first_packet, Server]).
-define(GLOBAL_DISTRIB_INCOMING_CLOSED(Server), [mod_global_distrib, incoming, closed, Server]).
-define(GLOBAL_DISTRIB_INCOMING_ERRORED(Server), [mod_global_distrib, incoming, errored, Server]).
-define(GLOBAL_DISTRIB_OUTGOING_ESTABLISHED, mod_global_distrib_outgoing_established).
-define(GLOBAL_DISTRIB_OUTGOING_CLOSED, mod_global_distrib_outgoing_closed).
-define(GLOBAL_DISTRIB_OUTGOING_ERRORED, mod_global_distrib_outgoing_errored).
-define(GLOBAL_DISTRIB_BOUNCE_QUEUE_SIZE, mod_global_distrib_bounce_queue_size).
