-type username() :: binary().
-type host() :: binary().
-type sender() :: binary().
-type content() :: binary().
-type count() :: binary().
-type id() :: binary().
-type get_inbox_res() :: list(inbox_res()).
-type inbox_res() :: {username(), content(), count()}.
-type inbox_write_res() :: ok | {error, any()}.
-type marker() :: binary().
