# Default cassandra version
CASSANDRA_VERSION=${CASSANDRA_VERSION:-3.9}

# Default ElasticSearch version
ELASTICSEARCH_VERSION=${ELASTICSEARCH_VERSION:-5.6.9}

MYSQL_VERSION=${MYSQL_VERSION:-8.0.20}

PGSQL_VERSION=${PGSQL_VERSION:-latest}

LDAP_VERSION=${LDAP_VESRION:-1.2.4}

REDIS_VERSION=${REDIS_VERSION:-6.2.6}

RMQ_VERSION=${RMQ_VERSION:-3.7-alpine}
