#!/bin/sh

## Debug?
set -x

## Fail if any of the steps fails.
set -e

## We assume configure.out is sourced already.
if [ -z "${MONGOOSEIM_CONFIGURED}" ]; then
    echo "Is configure.out sourced?" > /dev/fd/2
    exit 1
fi

INSTALL_DIR=${PREFIX}/mongooseim
if [ "${SYSTEM}" == "yes" ]; then
    BIN_DIR=${PREFIX}/bin
else
    BIN_DIR=
fi
# A separate RUNNER_GROUP is handy for testing on a Mac,
# where users don't have a group of the same name by default.
if [ -z "${RUNNER_GROUP}" ]; then
    RUNNER_GROUP=${RUNNER_USER}
fi

## Install!
INSTALL_OPTS="-o ${RUNNER_USER} -g ${RUNNER_GROUP}"
install $INSTALL_OPTS -d ${INSTALL_DIR}
cp -R rel/mongooseim/* ${INSTALL_DIR}
chown -R ${RUNNER_USER}:${RUNNER_GROUP} ${INSTALL_DIR}
## TODO: this sed line will become redundant once reltool is capable of putting correct values in
sed -e 's*\(RUNNER_USER=\).\**\1'"${RUNNER_USER}"'*' \
    rel/mongooseim/bin/mongooseim > ${INSTALL_DIR}/bin/mongooseim
if [ -n "${BIN_DIR}" ]; then
    install $INSTALL_OPTS -d ${BIN_DIR}
    install $INSTALL_OPTS rel/mongooseim/bin/mongooseimctl ${BIN_DIR}/mongooseimctl
    ## TODO: this sed line will become redundant once reltool is capable of putting correct values in
    sed -e 's*\(RUNNER_SCRIPT_DIR=\).\**\1'"${INSTALL_DIR}"'/bin*' \
        rel/mongooseim/bin/mongooseimctl > ${BIN_DIR}/mongooseimctl
    chmod 550 ${BIN_DIR}/mongooseimctl
fi

## Do the bookkeeping.
## TODO: How to automate this? If done manually, there's always space for a cock-up.
find ${INSTALL_DIR} > install.log
if [ "${SYSTEM}" == "yes" ]; then
    echo ${BIN_DIR} >> install.log
    echo ${BIN_DIR}/mongooseimctl >> install.log
fi
echo \# MongooseIM successfully installed to ${INSTALL_DIR} | tee -a install.log > /dev/fd/2
