#!/bin/bash



RIAK_HOST="http://localhost:8098"

curl -XPUT $RIAK_HOST/search/schema/vcard \
    -H 'Content-Type:application/xml' \
    --data-binary @tools/vcard_search_schema.xml

curl $RIAK_HOST/search/schema/vcard

curl -XPUT $RIAK_HOST/search/index/vcard \
    -H 'Content-Type: application/json' \
    -d '{"schema":"vcard"}'

curl -XPUT $RIAK_HOST/search/schema/mam \
    -H 'Content-Type:application/xml' \
    --data-binary @tools/mam_search_schema.xml

curl $RIAK_HOST/search/schema/mam

curl -XPUT $RIAK_HOST/search/index/mam \
    -H 'Content-Type: application/json' \
    -d '{"schema":"mam"}'

sleep 20

RIAK_ADMIN="docker exec -i mongooseim-riak riak-admin"

$RIAK_ADMIN bucket-type create users '{"props":{"datatype":"map"}}'
$RIAK_ADMIN bucket-type activate users

$RIAK_ADMIN bucket-type create rosters '{"props":{"datatype":"map"}}'
$RIAK_ADMIN bucket-type activate rosters

$RIAK_ADMIN bucket-type create roster_versions '{"props":{"last_write_wins":true, "dvv_enabled":false}}'
$RIAK_ADMIN bucket-type activate roster_versions

$RIAK_ADMIN bucket-type create private '{"props":{"last_write_wins":true, "dvv_enabled":false}}'
$RIAK_ADMIN bucket-type activate private

$RIAK_ADMIN bucket-type create vcard '{"props":{"last_write_wins":true, "search_index":"vcard", "dvv_enabled":false}}'
$RIAK_ADMIN bucket-type activate vcard

$RIAK_ADMIN bucket-type create mam_yz '{"props":{"datatype":"map", "search_index":"mam"}}'
$RIAK_ADMIN bucket-type activate mam_yz

$RIAK_ADMIN bucket-type create last '{"props":{"last_write_wins":true, "dvv_enabled":false}}'
$RIAK_ADMIN bucket-type activate last

$RIAK_ADMIN bucket-type create offline '{"props":{"last_write_wins":true, "dvv_enabled":false}}'
$RIAK_ADMIN bucket-type activate offline

$RIAK_ADMIN bucket-type create privacy_defaults '{"props":{"last_write_wins":true, "dvv_enabled":false}}'
$RIAK_ADMIN bucket-type activate privacy_defaults

$RIAK_ADMIN bucket-type create privacy_lists_names '{"props":{"datatype":"set"}}'
$RIAK_ADMIN bucket-type activate privacy_lists_names

$RIAK_ADMIN bucket-type create privacy_lists '{"props":{"last_write_wins":true,"dvv_enabled":false}}'
$RIAK_ADMIN bucket-type activate privacy_lists
