schema{
  query: AdminQuery,
  mutation: AdminMutation
}

"""
Contains all admin available queries.
Only an authenticated admin can execute these queries.
"""
type AdminQuery{
  "Get domains info"
  domains: DomainAdminQuery
  "Check authorization status"
  checkAuth: AuthStatus
  "Account management"
  account: AccountAdminQuery
  stanza: StanzaAdminQuery
}

"""
Contains all admin available mutations
Only an authenticated admin can execute these mutations.
"""
type AdminMutation @protected{
  "Account management"
  account: AccountAdminMutation
  "Modify domains properties or create/destroy domain"
  domains: DomainAdminMutation
  stanza: StanzaAdminMutation
}
