schema{
  query: AdminQuery,
  mutation: AdminMutation
}

"""
Contains all admin available queries.
Only an authenticated admin can execute these queries.
"""
type AdminQuery{
  "Check authorization status"
  checkAuth: AdminAuthInfo
  "Domain management"
  domains: DomainAdminQuery
  "Account management"
  account: AccountAdminQuery
  "Session management"
  session: SessionAdminQuery
  "Stanza management"
  stanza: StanzaAdminQuery
  "MUC room management"
  muc: MUCAdminQuery
  "MUC Light room management"
  muc_light: MUCLightAdminQuery
  "Roster/Contacts management"
  roster: RosterAdminQuery 
}

"""
Contains all admin available mutations.
Only an authenticated admin can execute these mutations.
"""
type AdminMutation @protected{
  "Account management"
  account: AccountAdminMutation
  "Domain management"
  domains: DomainAdminMutation
  "Session management"
  session: SessionAdminMutation
  "Stanza management"
  stanza: StanzaAdminMutation
  "MUC room management"
  muc: MUCAdminMutation
  "MUC Light room management"
  muc_light: MUCLightAdminMutation
  "Roster/Contacts management"
  roster: RosterAdminMutation
}
