"Allow admin to get information about CETS status"
type CETSAdminQuery @protected{
    "Get a list of tables from the local node. Only for global admin"
    tableInfo: [CETSTableInfo]
      @protected(type: GLOBAL)
    "Get status of CETS. Only for global admin"
    systemInfo: CETSSystemInfo
      @protected(type: GLOBAL)
}

type CETSTableInfo {
  "ETS table name"
  tableName: String
  "Memory (in words)"
  memory: Int
  "Size (in records)"
  size: Int
  "A list of clustered nodes"
  nodes: [String]
}

type CETSSystemInfo {
  "Unavailable nodes"
  unavailableNodes: [String]
  "Unavailable nodes count"
  unavailableNodesCount: Int
  "Available nodes (visible to the current node at this moment including the current node)"
  availableNodes: [String]
  "Available nodes count"
  availableNodesCount: Int
  "Joined nodes (replicate the same tables as the current node)"
  joinedNodes: [String]
  "Joined nodes count"
  joinedNodesCount: Int
  "Partially joined nodes (replicate a different list of tables)"
  partiallyJoinedNodes: [String]
  "Joined nodes count"
  partiallyJoinedNodesCount: Int
  "Discovered nodes (returned from the discovery backend)"
  discoveredNodes: [String]
  "Discovered nodes count"
  discoveredNodesCount: Int
  "Returns true if the last discovery attempt is successful"
  discoveryWorks: Boolean
}
