type DomainAdminQuery @protected{
  "Get all enabled domains by hostType"
  domainsByHostType(hostType: String!): [String!]
  "Get information about the domain"
  domainDetails(domain: String!): Domain
}

type DomainAdminMutation @protected{
  "Add new domain"
  addDomain(domain: String!, hostType: String!): Domain
  "Remove domain"
  removeDomain(domain: String!, hostType: String!): RemoveDomainPayload
  "Enable domain"
  enableDomain(domain: String!): Domain
  "Disable domain"
  disableDomain(domain: String!): Domain
}

"A result of domain removal"
type RemoveDomainPayload{
  "Success message"
  msg: String
  "Removed domain data"
  domain: Domain
}
