"""
Allow admin to generate upload/download URL for the file on user's behalf".
"""
type HttpUploadAdminMutation @protected{
    "Allow admin to generate upload/download URLs for the file on user's behalf"
    getUrl(user: JID!, filename: String!, size: Int!, contentType: String!, timeout: Int!): String
}