"""
Allow admin to manage last activity.
"""
type LastAdminQuery @protected{
  "Get the user's last activity information"
  getLast(user: JID!): LastActivity
    @protected(type: DOMAIN, args: ["user"])
  "Get the number of users active from the given timestamp"
  countActiveUsers(domain: String!, timestamp: DateTime): Int
    @protected(type: DOMAIN, args: ["domain"])
}

"""
Allow admin to get information about last activity.
"""
type LastAdminMutation @protected{
  "Set user's last activity information"
  setLast(user: JID!, timestamp: DateTime, status: String!): LastActivity
    @protected(type: DOMAIN, args: ["user"])
}
