"""
Allow admin to manage mnesia database
"""

type MnesiaAdminQuery {
    info(keys: [String!]!): [MnesiaInfo]
}

type MnesiaAdminMutation {
    setMaster(node: String!): String
    changeNodename(fromString: String!, toString: String!,
                         source: String!, target: String!): String
    backup(path: String!): String
    restore(path: String!): String
    dump(path: String!): String
    dumpTable(path: String!, table: String!): String
    load(path: String!): String
    installFallback(path: String!): String
}

union MnesiaInfo =  MnesiaStringResponse | MnesiaListResponse | MnesiaIntResponse

type MnesiaStringResponse {
    result: String
    key: String
}

type MnesiaListResponse {
    result: [String]
    key: String
}

type MnesiaIntResponse {
    result: Int
    key: String
}
