"""
Allow admin to manage mnesia database
"""

type MnesiaAdminQuery @protected{
  info(keys: [String!]!): [MnesiaInfo]
    @protected(type: GLOBAL)
}

type MnesiaAdminMutation @protected{
  setMaster(node: String!): String
    @protected(type: GLOBAL)
  changeNodename(fromString: String!, toString: String!,
                       source: String!, target: String!): String
    @protected(type: GLOBAL)
  backup(path: String!): String
    @protected(type: GLOBAL)
  restore(path: String!): String
    @protected(type: GLOBAL)
  dump(path: String!): String
    @protected(type: GLOBAL)
  dumpTable(path: String!, table: String!): String
    @protected(type: GLOBAL)
  load(path: String!): String
    @protected(type: GLOBAL)
  installFallback(path: String!): String
    @protected(type: GLOBAL)
}

union MnesiaInfo =  MnesiaStringResponse | MnesiaListResponse | MnesiaIntResponse

type MnesiaStringResponse {
  result: String
  key: String
}

type MnesiaListResponse {
  result: [String]
  key: String
}

type MnesiaIntResponse {
  result: Int
  key: String
}
