"""
Allow admin to manage Multi-User Chat rooms.
"""
type MUCAdminMutation @protected{
  "Create a MUC room under the given XMPP hostname"
  createInstantRoom(mucDomain: String!, name: String!, owner: JID!, nick: String!): MUCRoomDesc
  "Invite a user to a MUC room"
  inviteUser(room: JID!, sender: JID!, recipient: JID!, reason: String): String
  "Kick a user from a MUC room"
  kickUser(room: JID!, nick: String!, reason: String): String
  "Send a message to a MUC room, from with res"
  sendMessageToRoom(room: JID!, from: JID!, body: String!): String
  "Send a private message to a MUC room user, from with res"
  sendPrivateMessage(room: JID!, from: JID!, toNick: String!, body: String!): String
  "Remove a MUC room"
  deleteRoom(room: JID!, reason: String): String
  "Change configuration of a MUC room"
  changeRoomConfiguration(room: JID!, config: MUCRoomConfigInput!): MUCRoomConfig
  "Change a user role"
  setUserRole(room: JID!, nick: String!, role: MUCRole!): String
  "Change a user affiliation"
  setUserAffiliation(room: JID!, user: JID!, affiliation: MUCAffiliation!): String
  "Make a user enter the room with given nick"
  enterRoom(room: JID!, user: JID!, nick: String!, password: String): String
  "Make a user with the given nick exit the room"
  exitRoom(room: JID!, user: JID!, nick: String!): String
}

"""
Allow admin to get information about Multi-User Chat rooms.
"""
type MUCAdminQuery @protected{
  "Get MUC rooms under the given MUC domain"
  listRooms(mucDomain: String!, from: JID, limit: Int, index: Int): MUCRoomsPayload!
  "Get configuration of the MUC room"
  getRoomConfig(room: JID!): MUCRoomConfig
  "Get users list of given MUC room"
  listRoomUsers(room: JID!): [MUCRoomUser!]
  "Get affiliations list of given MUC room"
  listRoomAffiliations(room: JID!, affiliation: MUCAffiliation): [MUCRoomAffiliation!]
  "Get the MUC room archived messages"
  getRoomMessages(room: JID!, pageSize: Int, before: DateTime): StanzasPayload
}
