"""
Allow admin to manage Multi-User Chat Light rooms.
"""
type MUCLightAdminMutation @use(modules: ["mod_muc_light"]) @protected{
  "Create a MUC light room under the given XMPP hostname"
  createRoom(mucDomain: DomainName!, name: String, owner: JID!, subject: String, id: RoomName,
             options: [RoomConfigDictEntryInput!]): Room
    @protected(type: DOMAIN, args: ["mucDomain", "owner"]) @use(arg: "mucDomain")
  "Change configuration of a MUC Light room"
  changeRoomConfiguration(room: BareJID!, owner: JID!, name: String, subject: String,
                          options: [RoomConfigDictEntryInput!]): Room
    @protected(type: DOMAIN, args: ["room"]) @use(arg: "room")
  "Invite a user to a MUC Light room"
  inviteUser(room: BareJID!, sender: JID!, recipient: JID!): String
    @protected(type: DOMAIN, args: ["sender"]) @use(arg: "room")
  "Remove a MUC Light room"
  deleteRoom(room: BareJID!): String
    @protected(type: DOMAIN, args: ["room"]) @use(arg: "room")
  "Kick a user from a MUC Light room"
  kickUser(room: BareJID!, user: JID!): String
    @protected(type: DOMAIN, args: ["room"]) @use(arg: "room")
  "Send a message to a MUC Light room"
  sendMessageToRoom(room: BareJID!, from: JID!, body: String!): String
    @protected(type: DOMAIN, args: ["from"]) @use(arg: "room")
  "Set the user's list of blocked entities"
  setBlockingList(user: JID!, items: [BlockingInput!]!): String
    @protected(type: DOMAIN, args: ["user"]) @use(arg: "user")
}

"""
Allow admin to get information about Multi-User Chat Light rooms.
"""
type MUCLightAdminQuery @protected @use(modules: ["mod_muc_light"]){
  "Get the MUC Light room archived messages"
  getRoomMessages(room: BareJID!, pageSize: PosInt, before: DateTime): StanzasPayload
    @protected(type: DOMAIN, args: ["room"]) @use(arg: "room", modules: ["mod_mam_muc"])
  "Get configuration of the MUC Light room"
  getRoomConfig(room: BareJID!): Room
    @protected(type: DOMAIN, args: ["room"]) @use(arg: "room")
  "Get users list of given MUC Light room"
  listRoomUsers(room: BareJID!): [RoomUser!]
    @protected(type: DOMAIN, args: ["room"]) @use(arg: "room")
  "Get the list of MUC Light rooms that the user participates in"
  listUserRooms(user: JID!): [JID!]
    @protected(type: DOMAIN, args: ["user"]) @use(arg: "user")
  "Get the user's list of blocked entities"
  getBlockingList(user: JID!): [BlockingItem!]
    @protected(type: DOMAIN, args: ["user"]) @use(arg: "user")
}
