"""
Allow admin to delete offline messages from specified domain
"""
type OfflineAdminMutation @protected @use(modules: ["mod_offline"]){
    "Delete offline messages whose date has expired"
    deleteExpiredMessages(domain: DomainName!): String @use(arg: "domain")
      @protected(type: DOMAIN, args: ["domain"])
    "Delete messages at least as old as the number of days specified in the parameter"
    deleteOldMessages(domain: DomainName!, days: PosInt!): String
      @protected(type: DOMAIN, args: ["domain"]) @use(arg: "domain")
}
