"""
Allow admin to set the user's private data
"""
type PrivateAdminMutation @protected {
    "Set the user's private data"
    setPrivate(user: JID!, elementString: String!): String
      @protected(type: DOMAIN, args: ["user"])
}

"""
Allow admin to get the user's private data
"""
type PrivateAdminQuery @protected {
    "Get the user's private data"
    getPrivate(user: JID!, element: String!, nameSpace: String!): String
      @protected(type: DOMAIN, args: ["user"])
}
