"""
Allow admin to get and revoke user's auth tokens
"""
 type TokenAdminMutation @protected @use(modules: ["mod_auth_token"]){
    "Request auth token for a user"
    requestToken(user: JID!): Token
      @protected(type: DOMAIN, args: ["user"]) @use(arg: "user")
    "Revoke any tokens for a user"
    revokeToken(user: JID!): String
      @protected(type: DOMAIN, args: ["user"]) @use(arg: "user")
 }
