"""
Allow admin to set user's vcard
"""
type VcardAdminMutation @protected @use(modules: ["mod_vcard"]){
    "Set a new vcard for a user"
    setVcard(user: JID!, vcard: VcardInput!): Vcard
      @protected(type: DOMAIN, args: ["user"]) @use(arg: "user")
}

"""
Allow admin to get the user's vcard
"""
type VcardAdminQuery @protected @use(modules: ["mod_vcard"]){
    "Get the user's vcard"
    getVcard(user: JID!): Vcard
      @protected(type: DOMAIN, args: ["user"]) @use(arg: "user")
}
