schema{
  query: Query,
  mutation: Mutation
}

directive @protected (type: ProtectionType = DEFAULT, args: [String!] = [])
  on FIELD_DEFINITION | OBJECT

enum ProtectionType{
  DOMAIN
  GLOBAL
  DEFAULT
}

directive @use(modules: [String!] = [], services: [String!] = [], arg: String)
  on FIELD_DEFINITION | OBJECT

"""
Contains all available queries.
"""
type Query @protected{
  field: String
  command: String @use(modules: ["mod_x"], services: ["service_a"])
  fieldDP(argA: String): String
    @protected(type: DOMAIN, args: ["argA"])
  fieldGlobal(argA: String): String
    @protected(type: GLOBAL)
}

"""
Contains all available mutations.
"""
type Mutation{
  field: String
  id(value: String!): String
}
