schema{
  query: Query,
  mutation: Mutation
}

directive @protected (type: ProtectionType = DEFAULT, args: [String!] = [])
  on FIELD_DEFINITION | OBJECT

enum ProtectionType{
  DOMAIN
  DEFAULT
}

"""
Contains all available queries.
"""
type Query @protected{
  field: String
  fieldDP(argA: String): String @protected(type: DOMAIN, args: ["argA"])
}

"""
Contains all available mutations.
"""
type Mutation{
  field: String
  id(value: String!): String
}
