schema{
  query: UserQuery,
  mutation: UserMutation
}

directive @protected (type: ProtectionType = DEFAULT, args: [String!] = [])
  on FIELD_DEFINITION | OBJECT | INTERFACE

enum ProtectionType{
  DOMAIN
  GLOBAL
  DEFAULT
}

scalar JID

type UserQuery{
  field: String
  protectedField: String @protected
  domainProtectedField(argA: String, argB: String):
    String @protected(type: DOMAIN, args: ["argA"])
  domainInputProtectedField(argA: String, argB: DomainInput):
    String @protected(type: DOMAIN, args: ["argA", "argB.domain"])
  domainListInputProtectedField(domains: [DomainInput!]):
    String @protected(type: DOMAIN, args: ["domains.domain"])
  domainJIDProtectedField(argA: JID, argB: JID):
    String @protected(type: DOMAIN, args: ["argA"])
  onlyForGlobalAdmin: String @protected(type: GLOBAL)
  interface: Interface
  union: UnionT
  obj: Object
  protectedObj: ProtectedObject
  protInterface: ProtectedInterface 
  objProtInterface: ObjectImplProtInt
}

type UserMutation @protected{
  field: String
}

interface Interface{
  name: String
  otherName: String
  protectedName: String @protected
  protectedDomainName(domain: String):
    String @protected(type: DOMAIN, args: ["domain"])
  domainName(domain: String): String
}

interface ProtectedInterface @protected{
  name: String
}

type Object implements Interface{
  name: String
  otherName: String @protected
  protectedName: String
  protectedDomainName(domain: String): String
  domainName(domain: String):
    String @protected(type: DOMAIN, args: ["domain"])
  protectedField: String @protected
  domainProtectedField(argA: String, argB: String):
    String @protected(type: DOMAIN, args: ["argA"])
  field: String
}

type ProtectedObject implements Interface @protected{
  name: String
  otherName: String
  protectedName: String
  domainName(domain: String): String
  protectedDomainName(domain: String): String
  type: String
}

type ObjectImplProtInt implements ProtectedInterface{
  name: String
  field: String
}

type O1{
  field1: Int
  field1Protected: Int @protected
}

type O2 @protected{
  field2: Int
}

union UnionT = O1 | O2

input DomainInput{
  domain: String!
  notDomain: String
}
