#!/usr/bin/env bash

set -e

. env/build-run

PLATFORM=$1
[ x"$PLATFORM" = x"" ] && ( echo "$0: which platform container to run?"; exit 1 )

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd`
popd > /dev/null

TAG="$BUILD_CONTAINER_PREFIX.$PLATFORM.$BUILD_CONTAINER_SUFFIX"
docker run -it --hostname $PLATFORM --rm -v $SCRIPTPATH/packages:/packages $TAG bash
