#!/usr/bin/env bash

set -e

. env/build-run

PLATFORM=$1
[ x"$PLATFORM" = x"" ] && ( echo "$0: which platform container to run?"; exit 1 )

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd`
popd > /dev/null

docker run -it --hostname $PLATFORM --rm \
    -v $SCRIPTPATH/packages:/packages $BUILD_CONTAINER_PREFIX.$PLATFORM bash

